version: "3.9"

services:
  web_app_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "web_app_django"
    ports:
      - "8083:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - custom

  db:
    image: postgres:latest
    container_name: "db_django"
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    env_file:
      - .env
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  postgres_data:
